# Generated by Django 5.2.6 on 2025-09-12 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('image_to_pdf', 'Image to PDF'), ('pdf_merge', 'PDF Merge'), ('pdf_password', 'PDF Password Protection'), ('pdf_to_ppt', 'PDF to PowerPoint'), ('ocr_extraction', 'OCR Text Extraction')], max_length=20)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
